//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("en-US" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("Pistachio - WPF Resource Visualizer")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("Infragistics, Inc.")]
[assembly: AssemblyProductAttribute("Pistachio")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007-2008 by Infragistics, Inc.")]
[assembly: AssemblyVersionAttribute("1.0.2007.*")]
[assembly: AssemblyFileVersionAttribute("1.0.2007.*")]
